version: '3.8'

services:
  web:
    image: chatwoot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chatwoot}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DISABLE_EMBEDDED_SIDEKIQ=true
    depends_on:
      - postgres
      - redis
    networks:
      - default
      - coolify

  sidekiq:
    image: chatwoot:latest
    restart: always
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chatwoot}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    depends_on:
      - web
      - postgres
      - redis
    networks:
      - default

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-chatwoot_production}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chatwoot}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "if [ -n \"$$REDIS_PASSWORD\" ]; then exec redis-server --requirepass \"$$REDIS_PASSWORD\"; else exec redis-server; fi"]
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  postgres_data:
  redis_data:

networks:
  default:
  coolify:
    external: true


